<?php


if ( ! defined( 'WP_UNINSTALL_PLUGIN' ) ) {
	exit;
}

/* ---------------- Uninstall Cleanup ---------------- */

function reloadify_uninstall_cleanup_current_site() {
	// Checked per site: on multisite each site has its own choice, and the
	// main site's setting must not decide for every other site.
	if ( ! get_option( 'reloadify_delete_data_on_uninstall', false ) ) {
		return;
	}

	delete_option( 'reloadify_settings' );
	delete_option( 'reloadify_last_site_update' );
	delete_option( 'reloadify_performance' );
	delete_option( 'reloadify_speed_boost_enabled' );
	delete_option( 'reloadify_speed_options' );
	delete_option( 'reloadify_media_optimize_enabled' );
	delete_option( 'reloadify_media_format_preference' );
	delete_option( 'reloadify_delete_data_on_uninstall' );
	delete_option( 'reloadify_extras_settings' );

	// wp_unschedule_hook() also removes the per-video events, which carry an
	// attachment ID argument that wp_next_scheduled( $hook ) can't match.
	wp_unschedule_hook( 'reloadify_media_backfill_batch' );
	wp_unschedule_hook( 'reloadify_media_backfill_video_batch' );
	wp_unschedule_hook( 'reloadify_media_compress_video' );

	// Per-attachment bookkeeping written by Media Optimization.
	delete_post_meta_by_key( '_reloadify_media_optimized' );
	delete_post_meta_by_key( '_reloadify_media_video_optimized' );
	delete_post_meta_by_key( '_reloadify_media_stats' );

	$upload = wp_upload_dir();
	if ( empty( $upload['basedir'] ) ) {
		return;
	}

	require_once ABSPATH . 'wp-admin/includes/file.php';
	WP_Filesystem();

	global $wp_filesystem;
	if ( ! $wp_filesystem ) {
		return;
	}

	// The reload timestamp folder and the Speed Boost minification cache are
	// both generated by this plugin, so both go with it.
	$reloadify_generated_dirs = [
		trailingslashit( $upload['basedir'] ) . 'reloadify-reload',
		trailingslashit( $upload['basedir'] ) . 'reloadify-minify',
	];

	foreach ( $reloadify_generated_dirs as $dir ) {
		if ( is_dir( $dir ) ) {
			$wp_filesystem->delete( $dir, true );
		}
	}
}

if ( is_multisite() ) {
	$reloadify_site_ids = get_sites( [ 'fields' => 'ids' ] );

	foreach ( $reloadify_site_ids as $reloadify_site_id ) {
		switch_to_blog( $reloadify_site_id );
		reloadify_uninstall_cleanup_current_site();
		restore_current_blog();
	}
} else {
	reloadify_uninstall_cleanup_current_site();
}
